### ISSUE TITLE
[UserStory] Create GitHub page for product

### ISSUE THREAD

**Issue by BatchOfAllTrades** [OptiCut/OptiCut#20]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a** developer 
**I want**  a product page 
**so that** information about the plugin is easily accessible to the end user.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ a GitHub page with product information.
* _Rule 2_ the page contains information about how to use the plugin

**Comment by cdinh92** [comment]
Create another repository called "opticut.github.io" at https://github.com/OptiCut/opticut.github.io and the GitHub page now can be found at https://opticut.github.io
